
- name: Deploy HAProxy
  ansible.builtin.import_playbook: deploy_haproxy.yml

- name: Deploy Web Server
  ansible.builtin.import_playbook: deploy_apache.yml

- name: Deploy Web App
  ansible.builtin.import_playbook: deploy_webapp.yml

