---
- name: Deploy simple Message of the Day
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Populate MOTD
      template:
        src: templates/motd.j2
        dest: /etc/motd.d/motd_updated

#    - name: Remove other messages
#      file:
#        path: "/etc/motd.d/{{ item }}"
#        state: absent
#      loop:
#        - insights-client
#        - cockpit
