---
- name: Implement a basic webserver
  hosts: webservers
  vars:
    packages:
      - httpd
      - httpd-devel

  tasks:
    - name: Install the webserver software
      ansible.builtin.yum:
        name: "{{packages}}"
        state: installed

    - name: Start and persistently enable httpd
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Open the port in the firewall
      firewall:
        service: http
        state: enabled
        immediate: true
        permanent: true

    - copy:
        content: "Hello world\n"
        dest: /var/www/html/index.html

    - name: Smoke Test
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}"
        return_content: true
        status_code: 200
      register: response
      delegate_to: localhost
      become: false
      failed_when: '"Hello World" not in response.content'

...
