---
- name: Test running playbook from controller
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - firewalld
          - httpd
        state: latest

    - name: firewalld enabled and running
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: httpd enabled and running
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: test html page is installed
      ansible.builtin.copy:
        content: "Successful playbook run from automation controller.\n"
        dest: /var/www/html/index.html
...
