---

- name: Ensure Apache is deployed
  hosts: web_servers
  force_handlers: true
  gather_facts: false

  roles:
    # Apache-specific firewall rules are defined
    # in the 'apache_firewall_rules' variable
    - role: apache

