- name: Look at Vars
  hosts: servera.lab.example.com

  tasks:
    - set_fact:
        _firewall_variables_list: "{{ hostvars[inventory_hostname].keys() | select('match', '[a-z_]*_firewall_rules') | list }}"
    - debug:
        var: _firewall_variables_list

    - set_fact:
        firewall_rules: "{{ _firewall_variables_list | map('extract', hostvars[inventory_hostname]) | flatten | list  }}"
    - debug:
        var: firewall_rules
