---
- name: Ensure Apache is deployed
  hosts: web_servers
  force_handlers: true
  gather_facts: false

  roles:
    # Use the apache_firewall_rules.yml.j2 template to
    # generate the firewall rules.
    - role: apache
      firewall_rules: []
