---
- name: Upgrade Web Application
  hosts: web_servers
  become: true
  # TODO: Configure max allowable failures
  # TODO: Configure batches

  # TODO: Add a pre-task to disable each web server

  roles:
  - role: webapp

  post_tasks:
    - name: Smoke Test - Ensure HTTP 200 OK
      ansible.builtin.uri:
        url: "http://localhost:{{ apache_port }}"
        status_code: 200
      become: true

    # TODO: Add a post-task to re-enable each web server
