from paglibs import *
import time

time.sleep(10)

pag.typewrite("lab start inventory-review")
et()
time.sleep(70)
print('done running')
pag.typewrite("mkdir git-repos")
et()
pag.typewrite("cd git-repos")
et()
pag.typewrite("git clone https://git.lab.example.com/student/inventory-review.git")
et()
pag.typewrite("cd inventory-review")
et()
pag.typewrite("git checkout -b exercise")
et()
pag.typewrite("ansible-navigator run -m stdout site.yml")
et()
time.sleep(60)
pag.typewrite("for x in {1..2}; do curl servera; done")
et()
pag.typewrite("mkdir -pv group_vars/{a,b}_web_servers")
et()
pag.typewrite('echo "webapp_version: v1.1a" > group_vars/a_web_servers/webapp.yml')
et()
pag.typewrite('echo "webapp_version: v1.1b" > group_vars/b_web_servers/webapp.yml')
et()
pag.typewrite("ansible-navigator run -m stdout deploy_webapp.yml")
et()
time.sleep(60)
pag.typewrite("for x in {1..2}; do curl servera; done")
et()
pag.typewrite("git add .")
et()
pag.typewrite('git commit -m "Created variable files for the A and B groups."')
et()
pag.typewrite("ansible-navigator inventory -i inventory --list --yaml -m stdout > inventory.yml")
et()
pag.typewrite("mv ~/dev/build-environments/devenv/do374-exercises/files/do374-inventory-review-inventory.yml ./inventory.yml")
et()
pag.typewrite('ansible-navigator run -m stdout site.yml -i inventory.yml')
time.sleep(60)
pag.typewrite("for x in {1..2}; do curl servera; done")
et()
pag.typewrite("git add inventory.yml")
et()
pag.typewrite('git commit -m "Added YAML inventory"')
et()
pag.typewrite("git push -u origin exercise")
et()
time.sleep(2)
pag.PAUSE = 2
pag.typewrite("Student@123")
et()
#pag.typewrite("lab grade inventory-review")
et()
# pag.typewrite("lab start inventory-review")
# et()
